#!/usr/bin/env bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew analytics off

brew install --cask firefox
brew install --cask rectangle
brew install --cask visual-studio-code
brew install --cask 1password
brew install --cask iterm2
