#!/usr/bin/env bash

DOTFILES=${PWD%/*}

git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.s status

git config --global include.path $DOTFILES/osx/git/.gitconfig
git config --global core.excludesfile $DOTFILES/osx/git/.gitignore
